# Generated by Django 6.0.3 on 2026-03-28 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Художник',
                'verbose_name_plural': 'Художники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Роспись',
                'verbose_name_plural': 'Росписи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sculptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Скульптор',
                'verbose_name_plural': 'Скульпторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MilkJug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название предмета')),
                ('year', models.CharField(blank=True, max_length=50, verbose_name='Год создания / период')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('factory', models.CharField(blank=True, max_length=255, verbose_name='Завод / фабрика')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Высота (см)')),
                ('volume', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Объем (мл)')),
                ('condition', models.CharField(blank=True, choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('satisfactory', 'Удовлетворительное'), ('poor', 'Плохое'), ('damaged', 'Поврежден')], max_length=20, verbose_name='Состояние')),
                ('has_mark', models.BooleanField(default=False, verbose_name='Наличие клейма')),
                ('mark_description', models.TextField(blank=True, verbose_name='Описание клейма')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Источник поступления')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('visibility', models.CharField(choices=[('public', 'Публичный'), ('registered', 'Только для зарегистрированных'), ('private', 'Приватный')], default='private', max_length=20, verbose_name='Видимость')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_jugs', to='catalog.artist', verbose_name='Художник')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_jugs', to='catalog.form', verbose_name='Форма')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_jugs', to='catalog.manufacturer', verbose_name='Производитель')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_jugs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('painting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_jugs', to='catalog.painting', verbose_name='Роспись')),
                ('sculptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_jugs', to='catalog.sculptor', verbose_name='Скульптор')),
            ],
            options={
                'verbose_name': 'Молочник',
                'verbose_name_plural': 'Молочники',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='milk_jugs/%Y/%m/%d/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('milk_jug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.milkjug', verbose_name='Молочник')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['order', '-is_main', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='milkjug',
            index=models.Index(fields=['manufacturer', 'form', 'painting'], name='catalog_mil_manufac_6ea819_idx'),
        ),
        migrations.AddIndex(
            model_name='milkjug',
            index=models.Index(fields=['owner', 'visibility'], name='catalog_mil_owner_i_6942b1_idx'),
        ),
    ]
